[package]
name = "insh"
version = "0.6.0"
edition = "2021"

[dependencies]
rustyline = "14.0.0"
dirs = "5.0.1"
once_cell = "1.19.0"

[features] 
default = ["with-file-history"]
with-file-history = []

[build]
rustflags = "--cfg with-file-history"
